name: flu_avm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  audioplayers: ^6.6.0
  dio: ^5.9.2
  flame: ^1.37.0
  flame_audio: ^2.12.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.2
  google_fonts: ^8.1.0
  mapbox_maps_flutter: ^2.24.2
  pie_chart: ^5.4.0
  socket_io_client: ^3.1.4
  video_player: ^2.11.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconos/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/iconos/
    - assets/
    - assets/videos/
    - assets/images/
    - assets/audio/
